name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y pkg-config
            sudo apt-get install -y musl-tools
      - name: Install Rust toolchain
        run: rustup toolchain install stable-x86_64-unknown-linux-gnu
      - name: Set Rust toolchain
        run: rustup default stable-x86_64-unknown-linux-gnu
      - name: Install musl target
        run: rustup target add x86_64-unknown-linux-musl
      - name: Check Rust version
        run: rustc --version
      - name: Fetch dependencies
        run: cargo fetch
      - name: Compile
        run: cargo build --release --target x86_64-unknown-linux-musl
      - name: Move binary
        run: mv target/x86_64-unknown-linux-musl/release/healthmonitor healthmonitor
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: healthmonitor
