name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: rustup toolchain install stable-x86_64-unknown-linux-gnu
      - name: Set Rust toolchain
        run: rustup default stable-x86_64-unknown-linux-gnu
      - name: Check Rust version
        run: rustc --version
      - name: Fetch dependencies
        run: cargo fetch
      - name: Compile
        run: cargo build --release --target x86_64-unknown-linux-gnu
      - name: Move binary
        run: mv target/x86_64-unknown-linux-gnu/release/healthmonitor healthmonitor
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: healthmonitor
